### ISSUE TITLE
about the datasets

### ISSUE THREAD

**Issue by jiejiangd** [YangHM/Convolutional-Prototype-Learning#5]
I'd like to ask if anyone can share the author's MNIST. At present, the author hasn't replied to me.Thank you very much!

**Comment by YangHM** [comment]
> I'd like to ask if anyone can share the author's MNIST. At present, the author hasn't replied to me.Thank you very much!

Hi, maybe the email is blocked, could you email me again then I can send you the dataset.

**Comment by jiejiangd** [comment]
> > I'd like to ask if anyone can share the author's MNIST. At present, the author hasn't replied to me.Thank you very much!
> 
> Hi, maybe the email is blocked, could you email me again then I can send you the dataset.

I just sent it to you. Thank you for sharing
